### ISSUE TITLE
Rebuild ja l10n community - todo list

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/gecko-l10n#392]
* [ ] Write a contribution guide for products l10n.
  - What we are doing.
  - How to do it.
  - How to participate on.
* [ ] Have periodic community meetings (once par month or quarter).
  - It's open meeting.
  - Just report our work.
  - Answer to any question.
* [ ] Connect Mozilla and Japanese users.
  - Tell some featured Mozilla news via SNS.
  - Tell what we (I) think about current issue or situation.

**Comment by marsf** [comment]
覚え書き。

> Write a contribution guide for products l10n. 

2023-08-19 に開催された [Firefox Localization Meetup (日本語化に参加してみよう)](https://mozilla.doorkeeper.jp/events/161698) のプレゼン資料を Wiki に書き起こす。

> Have periodic community meetings (once par month or quarter).

ミートアップが良い感じだったので、年に 1, 2 回は定期的に開催したい。
